using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using org.SpocWeb.root.Attributes;

namespace org.SpocWeb.root.maths.pga.ga;

/// <summary> 1D <a href='https://en.wikipedia.org/wiki/Dual_number'
/// >Dual/Projective Numbers</a>: Translation only </summary>
/// <remarks>
/// Similar to <see cref="R010"/>, the Complex Numbers,
/// this defines a Geometry with translation (instead of Rotation) generated by �.
/// Translations can be represented as rotations with an infinite radius.
///
/// Since �� = 0 the exponential Map exp(a�) = 1 + a� + a��� +... = 1 + a� 
/// describes a simple Translation by a.
/// 
/// The Sandwich Product simplifies too:
/// 
/// exp(a�) P exp(-a�) = (1 + a�) P ~(1 - a�) = (1+a�)P(1+a�)=P(1+2a�+0)= P + 2a� 
/// 
/// </remarks>
[DocState(Pass = 2, MTime = "2026-05-24T15:36:37Z", Digest = "0536cf067b342131b2ea9d3a5dd5ba2be20c3bff0b86a77c0709becd6f7ff765", Stale = false, Path = "ga/R001.cs", Since = "2026-10-06")]
[Facets(Layer = "domain", Status = "stable", Complexity = 2)]
[Tags("code/clifford_algebra", "code/dual_numbers")]
[System.ComponentModel.Description("1D Dual/Projective Numbers: Translation only")]
[Concept("Mathematics\\Geometry\\Geometric_Algebra.md")]
public class R001 : AGeoGebra2<R001>
{
	/// <summary>Gets the _ Basis.</summary>
	static readonly string[] _Basis = { "","d" };
	/// <inheritdoc />
	/// <example>
	/// <code language="yaml">
	/// pass: 2
	/// mtime: 2026-05-24T15:36:37Z
	/// digest: cae321e3ffc476a8af0bcd5db5fb714b7edcd03196b81ba47da92af87ac9ddfb
	/// </code>
	/// </example>
	public override IReadOnlyList<string> Basis => _Basis;

	/// <inheritdoc />
	public override R001 Self() => this;

	/// <summary> Base-Blades in 3D, usable as Indices for Components </summary>
	/// <remarks>
	/// ## Public Methods
	///
	/// | Line | Method | Description |
	/// |--:|---|---|
	/// | 64 | <see cref="_1_"/> | [0] Scalar e.g. Dot Product or oriented Volume |
	/// | 67 | <see cref="d"/> | [1] Homogenous Component e0� = 0 |
	/// | 70 | <see cref="_0"/> | No Component; signals both the End of Components and 0-Elements in the Cayley Tables below |
	/// </remarks>
	[DocState(Pass = 2, MTime = "2026-06-17T05:58:35Z", Digest = "19d8b601c33170797e5751504b527742b91970eda8a24342edc1ea4f3c6686aa", Stale = false, Path = "ga/R001.cs", Since = "2026-10-06")]
	[Facets(Layer = "domain", Status = "stable", Complexity = 1)]
	[Tags("code/enum", "code/clifford_algebra")]
	[System.ComponentModel.Description("Base-Blades in 3D, usable as Indices for Components")]
	[SuppressMessage("ReSharper", "InconsistentNaming")]
	[Concept("Mathematics\\Geometry\\Geometric_Algebra.md")]
	public enum Base : sbyte
	{
		/// <summary> [0] Scalar e.g. Dot Product or oriented Volume </summary>
		_1_,

		/// <summary> [1] Homogenous Component e0� = 0 </summary>
		d,

		/// <summary> No Component; signals both the End of Components and 0-Elements in the Cayley Tables below </summary>
		_0,// = sbyte.MinValue
	}

	#region Cayley Tables for different Products in R0,0,1

	/// <summary>Gets the _ Product Outer.</summary>
	static readonly Base[][] _ProductOuter = {
		new[] {Base._1_, Base.d},
		new[] {Base.d, Base._0},
	};

	/// <summary>Gets the product Outer.</summary>
	public static readonly IReadOnlyList<IReadOnlyList<Base>> ProductOuter = _ProductOuter;

	/// <summary>Gets the _ Product Geometric.</summary>
	static readonly Base[][] _ProductGeometric = {
		new[] {Base._1_, Base.d},
		new[] {Base.d, Base._0},
	};

	/// <summary>Gets the product Geometric.</summary>
	public static readonly IReadOnlyList<IReadOnlyList<Base>> ProductGeometric = _ProductGeometric;

	/// <summary>Gets the _ Product Dot.</summary>
	static readonly Base[][] _ProductDot = {
		new[] {Base._1_, Base.d}, 
		new[] {Base.d, Base._0},
	};

	/// <summary>Gets the product Dot.</summary>
	public static readonly IReadOnlyList<IReadOnlyList<Base>> ProductDot = _ProductDot;

	/// <summary>Gets the _ Products.<br/>
	/// Gets the products.</summary>
	static readonly Base[][][] _Products = { _ProductGeometric, _ProductDot, _ProductOuter};
	/// <summary>Gets the products.</summary>
	public static readonly IReadOnlyList<IReadOnlyList<IReadOnlyList<Base>>> Products = _Products;

	#endregion Cayley Tables for different Products in R3,0,0

	#region basis blades
	public static R001 E0 = new(1f, 1);
	public static R001 _1_ = new(1f, 0);

	/// <summary>Gets the _ Blades.<br/>
	/// Gets the blades.</summary>
	static readonly R001[] _Blades = {_1_, E0};
	/// <summary>Gets the blades.</summary>
	public static readonly R001[] Blades = _Blades;
	#endregion basis blades

	/// <summary> Creates a new <see cref="R001"/> multivector from the given component array. </summary>
	///
	[Facets(Layer = "domain", Status = "stable", Complexity = 2)]
	[Tags("code/clifford_algebra", "code/dual_numbers")]
	[System.ComponentModel.Description("Creates a new R001 multivector from the given component array.")]
	[Concept("Mathematics\\Geometry\\Geometric_Algebra.md")]
	public static R001 New(params float[] f) => New((IReadOnlyList<float>) f);
	/// <inheritdoc cref="New(float[])"/>
	public static R001 New(IReadOnlyList<float> f) => new(f);
	/// <inheritdoc cref="New(float[])"/>
	public static R001 New(double f = 0, int idx = 0) => new(f, idx);
	/// <inheritdoc cref="New(float[])"/>
	public static R001 New(double f = 0, Base idx = 0) => new(f, idx);

	/// <inheritdoc />
	public override R001 Create(IReadOnlyList<float> values) => new(values);
	/// <inheritdoc cref="Create(IReadOnlyList{float})"/>
	public override R001 Create(IList<float> values) => new((IReadOnlyList<float>)values);
	/// <inheritdoc />
	protected override R001 Create_(float[] values) => new(values);

	/// <summary>Gets or sets the element at the specified <paramref name="index"/>.</summary>
	///
	[Facets(Layer = "domain", Status = "stable", Complexity = 2)]
	[Tags("code/clifford_algebra", "code/dual_numbers")]
	[System.ComponentModel.Description("Gets or sets the element at the specified index.")]
	[Concept("Mathematics\\Geometry\\Geometric_Algebra.md")]
	public float this[Base idx] => _C[(int) idx];

	/// <summary>Initializes a new instance of <see cref="R001"/> with the specified <paramref name="f"/> and <paramref name="idx"/>.<br/>
	/// Initializes a new instance of <see cref="R001"/> with the specified <paramref name="f"/> and <paramref name="idx"/>.</summary>
	///
	[Facets(Layer = "domain", Status = "stable", Complexity = 2)]
	[Tags("code/clifford_algebra", "code/dual_numbers")]
	[System.ComponentModel.Description("Initializes a new instance of R001 with the specified f and idx. Initializes a new instance of R001 with the specified f and idx.")]
	[Concept("Mathematics\\Geometry\\Geometric_Algebra.md")]
	public R001(double f = 0, Base idx = 0) : base(f, (int)idx) {}
	/// <summary>Initializes a new instance of <see cref="R001"/> with the specified <paramref name="f"/> and <paramref name="idx"/>.</summary>
	///
	[Facets(Layer = "domain", Status = "stable", Complexity = 2)]
	[Tags("code/clifford_algebra", "code/dual_numbers")]
	[System.ComponentModel.Description("Initializes a new instance of R001 with the specified f and idx.")]
	[Concept("Mathematics\\Geometry\\Geometric_Algebra.md")]
	public R001(double f = 0, int idx = 0) : base(f, idx) {}

	/// <summary> Unchecked private Constructor for Speed </summary>
	///
	[Facets(Layer = "domain", Status = "stable", Complexity = 2)]
	[Tags("code/clifford_algebra", "code/dual_numbers")]
	[System.ComponentModel.Description("Unchecked private Constructor for Speed")]
	[Concept("Mathematics\\Geometry\\Geometric_Algebra.md")]
	R001(float[] f) : base(f) {}

	/// <summary> Checked Constructor with Copy </summary>
	///
	[Facets(Layer = "domain", Status = "stable", Complexity = 2)]
	[Tags("code/clifford_algebra", "code/dual_numbers")]
	[System.ComponentModel.Description("Checked Constructor with Copy")]
	[Concept("Mathematics\\Geometry\\Geometric_Algebra.md")]
	public R001(IReadOnlyList<float> values) : base(values) {}

	/// <inheritdoc />
	public override double Norm() => Math.Abs(_C[0]);
	/// <inheritdoc />
	public override double NormSqr() => _C.NormSqr2R001();

	/// <summary> Ideal norm. (signed) </summary>
	///
	[Facets(Layer = "domain", Status = "stable", Complexity = 2)]
	[Tags("code/clifford_algebra", "code/dual_numbers")]
	[System.ComponentModel.Description("Ideal norm. (signed)")]
	[Concept("Mathematics\\Geometry\\Geometric_Algebra.md")]
	public override double NormI() => this[1] != 0 ? this[1] : Norm();

	/// <inheritdoc />
	public override R001 Dual() => new(_C.Dual2());

	/// <inheritdoc />
	public override R001 Dot(IReadOnlyList<float> that) => new(_C.Dot2R001P(that));
	/// <inheritdoc />
	public override R001 Join(IReadOnlyList<float> that) => new(_C.Join2(that));
	/// <inheritdoc />
	public override R001 Meet(IReadOnlyList<float> that) => new(_C.Meet2(that));
	/// <inheritdoc />
	public override R001 MeetR(IReadOnlyList<float> that) => new(that.Meet2(_C));
	/// <inheritdoc />
	public override R001 Times(IReadOnlyList<float> factor) => new(_C.Times2R001P(factor));
	/// <inheritdoc />
	public override R001 TimesR(IReadOnlyList<float> factor) => new(factor.Times2R001P(_C));

	/// <inheritdoc />
	protected override double[][] Coefficients() => throw new NotSupportedException();
}

